name: build windows d3d12

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x86, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1.1
      - shell: cmd
        run: |
          msbuild ./build-windows/Demo-Windows-D3D12.sln /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}}
